### ISSUE TITLE
Rerun specs on save

### ISSUE THREAD

**Issue by louim** [foneandrew/ruby-spec-runner#7]
Hello! Thanks for this extension. Would it be feasible to have an option to allow rerunning (all / failed / last ran) specs automatically when the file is saved?

**Comment by foneandrew** [comment]
Hmm not sure? I don't have a lot of time to look into this now sorry (will add it to my todo list), but in the meantime would it work to configure the save shortcut to also trigger a test run? On a mac I can do this by adding the following to my `keybindings.json`:

```json
    {
        "key": "cmd+s",
        "command": "ruby-spec-runner.runRspecOrMinitestFile",
        "when": "editorLangId == ruby"
    }
```

Although that will mean you run tests for non spec files though 🤔 . Maybe there is a way to make the "when" more specific to spec files?
